/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg2;

import javax.swing.JOptionPane;
import gui.LibraryManagement;
import pkg2.ViewIssued;
import java.io.FileNotFoundException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class LibrarianSecFrame extends javax.swing.JFrame {

    /**
     * Creates new form LibrarianSecFrorm
     */
    public LibrarianSecFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addBook = new javax.swing.JButton();
        Dbook = new javax.swing.JButton();
        Ibook = new javax.swing.JButton();
        Dbook2 = new javax.swing.JButton();
        Rbook = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("  Librarian Section");

        addBook.setBackground(new java.awt.Color(204, 204, 255));
        addBook.setForeground(new java.awt.Color(0, 0, 255));
        addBook.setText("Add Books");
        addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookActionPerformed(evt);
            }
        });

        Dbook.setBackground(new java.awt.Color(204, 204, 255));
        Dbook.setForeground(new java.awt.Color(0, 0, 255));
        Dbook.setText("View Books");
        Dbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DbookActionPerformed(evt);
            }
        });

        Ibook.setBackground(new java.awt.Color(204, 204, 255));
        Ibook.setForeground(new java.awt.Color(0, 0, 255));
        Ibook.setText("Issue Book");
        Ibook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IbookActionPerformed(evt);
            }
        });

        Dbook2.setBackground(new java.awt.Color(204, 204, 255));
        Dbook2.setForeground(new java.awt.Color(0, 0, 255));
        Dbook2.setText("View Issued Books");
        Dbook2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dbook2ActionPerformed(evt);
            }
        });

        Rbook.setBackground(new java.awt.Color(204, 204, 255));
        Rbook.setForeground(new java.awt.Color(0, 0, 255));
        Rbook.setText("Return Book");
        Rbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbookActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(204, 204, 255));
        logout.setForeground(new java.awt.Color(0, 0, 255));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Rbook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Dbook2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(Ibook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Dbook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addBook)
                .addGap(26, 26, 26)
                .addComponent(Dbook)
                .addGap(26, 26, 26)
                .addComponent(Ibook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(Dbook2)
                .addGap(26, 26, 26)
                .addComponent(Rbook)
                .addGap(26, 26, 26)
                .addComponent(logout)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        LibraryManagement x = new LibraryManagement();
        this.setVisible(false);
        x.setLocationRelativeTo(null);
        x.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookActionPerformed

// TODO add your handling code here:
        this.setVisible(false);
        BookFrame x = new BookFrame();
        x.setLocationRelativeTo(null);
        x.setVisible(true);
    }//GEN-LAST:event_addBookActionPerformed

    private void DbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DbookActionPerformed
       
        try {
            // TODO add your handling code here:
            
            this.setVisible(false);
            DbookFrame x;
            x = new DbookFrame();
            x.setLocationRelativeTo(null);
            x.setVisible(true);
        } catch (FileNotFoundException | ParseException ex) {
            Logger.getLogger(LibrarianSecFrame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_DbookActionPerformed

    private void IbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IbookActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        IbookFrame x = new IbookFrame();
        x.setLocationRelativeTo(null);
        x.setVisible(true);
    }//GEN-LAST:event_IbookActionPerformed

    private void RbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbookActionPerformed
        // TODO add your handling code here:
        RbookFrame x = new RbookFrame();
        this.setVisible(false);
        x.setLocationRelativeTo(null);
        x.setVisible(true);

    }//GEN-LAST:event_RbookActionPerformed

    private void Dbook2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dbook2ActionPerformed
        try {
            // TODO add your handling code here:
            ViewIssued x = new ViewIssued();
            this.setVisible(false);
            x.setLocationRelativeTo(null);
            x.setVisible(true);
        } catch (FileNotFoundException | ParseException ex) {
            Logger.getLogger(LibrarianSecFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Dbook2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianSecFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianSecFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianSecFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianSecFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
             new LibrarianSecFrame().setVisible(true);
        }
         });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dbook;
    private javax.swing.JButton Dbook2;
    private javax.swing.JButton Ibook;
    private javax.swing.JButton Rbook;
    private javax.swing.JButton addBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
